### ISSUE TITLE
Error when running "python config.py train discrete_tcnn1"

### ISSUE THREAD

**Issue by zrachlin** [gy20073/BDD_Driving_Model#4]
I get the following message when I run "python config.py train discrete_tcnn1". I can't find anything about conv1/weights/Momentum, so I'm not sure what to do. Can you help with this? Thanks!

Traceback (most recent call last):
  File "train.py", line 583, in <module>
    tf.app.run()
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 580, in main
    train()
  File "train.py", line 399, in train
    apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/momentum.py", line 66, in _create_slots
    self._zeros_slot(v, "momentum", self._name)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv1/weights/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by gy20073** [comment]
Can you post the whole output log? 
What version of tensor flow are you using?

**Comment by zrachlin** [comment]
I am using tensorflow-gpu 1.3.0 with Anaconda. Here is the entire output log:

zrachlin@Pulsar:~/Documents/BDD_Driving_Model$ python config.py train discrete_tcnn1
('subset', 'train')
('n_sub_frame', 108)
('pretrained_model_checkpoint_path', '')
('learning_rate_decay_factor', 0.5)
('train_stage_name', 'stage_all')
('tensorboard_port', 7271)
('balance_drop_prob', -1.0)
('stop_future_frames', 1)
('no_slight_turn', True)
('data_provider', 'nexar_large_speed')
('checkpoint_dir', 'data/discrete_tcnn1')
('lstm_hidden_units', '64')
('clip_gradient_threshold', 10.0)
('decode_downsample_factor', 1)
('cnn_fc_hidden_units', 64)
('image_network_arch', 'CaffeNet')
('data_dir', 'data/tfrecords')
('enable_basenet_dropout', True)
('pretrained_model_path', 'data/tf.caffenet.bin')
('add_avepool_after_dim_reduction', True)
('history_window', 1)
('unique_experiment_name', 'discrete_tcnn1')
('num_readers', 4)
('add_dim_reduction', False)
('speed_limit_as_stop', 2.0)
('temporal_downsample_factor', 5)
('momentum', 0.99)
('profile', False)
('input_queue_memory_factor', 8)
('training_step_offset', 24732)
('optimizer', 'sgd')
('num_epochs_per_decay', 4)
('no_batch_norm', True)
('examples_per_shard', 1)
('release_batch', True)
('ego_previous_nstep', 30)
('batch_size', 1)
('display_summary', 100)
('add_dropout_layer', False)
('weight_decay_exclude_bias', False)
('num_preprocess_threads', 8)
('use_MIMO_inputs_pipeline', True)
('sub_arch_selection', 'car_discrete')
('eval_dir', 'data/discrete_tcnn1/eval')
('log_device_placement', False)
('subsample_factor', 1)
('resize_images', '228,228')
('model_definition', 'car_stop_model')
('num_gpus', 1)
('deceleration_thres', 1)
('train_dir', 'data/discrete_tcnn1')
('num_batch_join', 8)
('display_loss', 10)
('initial_learning_rate', 0.0001)
('arch_selection', 'CNN_FC')
('max_steps', 10000000)
('checkpoint_interval', 5000)
('cnn_feature', 'drop7')
<module 'tensorflow' from '/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.pyc'>
data/tfrecords IN DATA_FILES
Glob Files Done...
output batch of parse_example_proto == required batchsize (1), no batching needed
Omitting the batch_join queue
buffer queue capacity is:  8  batches
---------------------------------------- enable basenet dropout
using Yang's load pretrained weights version
('conv1', 'weights', (11, 11, 3, 96))
('weight = ', 0.0)
('conv1', 'biases', (96,))
(108, 55, 55, 96)
('conv2', 'weights', (5, 5, 48, 256))
('weight = ', 0.0)
('conv2', 'biases', (256,))
(108, 27, 27, 256)
('conv3', 'weights', (3, 3, 256, 384))
('weight = ', 0.0)
('conv3', 'biases', (384,))
(108, 13, 13, 384)
('conv4', 'weights', (3, 3, 192, 384))
('weight = ', 0.0)
('conv4', 'biases', (384,))
(108, 13, 13, 384)
('conv5', 'weights', (3, 3, 192, 256))
('weight = ', 0.0)
('conv5', 'biases', (256,))
(108, 13, 13, 256)
('fc6', 'weights', (9216, 4096))
('weight = ', 0.0)
('fc6', 'biases', (4096,))
(108, 1, 1, 4096)
('fc7', 'weights', (4096, 4096))
('weight = ', 0.0)
('fc7', 'biases', (4096,))
(108, 1, 1, 4096)
('fc8', 'weights', (4096, 1000))
('weight = ', 0.0)
('fc8', 'biases', (1000,))
(108, 1, 1, 1000)
---------------------------------------- TrainStage1_discrete_tcnn1
----------------------------------------
All tensors that will be summarized:
Tensor("tower_0/TrainStage1_discrete_tcnn1/temporal_conv/Relu:0", shape=(1, 108, 1, 64), dtype=float32, device=/device:GPU:0)
Tensor("tower_0/TrainStage1_discrete_tcnn1/softmax_linear_car_discrete/BiasAdd:0", shape=(108, 6), dtype=float32, device=/device:GPU:0)
----------------------------------------
 gradient will be computed for vars:
conv1/weights
conv1/biases
conv2/weights
conv2/biases
conv3/weights
conv3/biases
conv4/weights
conv4/biases
conv5/weights
conv5/biases
fc6/weights
fc6/biases
fc7/weights
fc7/biases
fc8/weights
fc8/biases
TrainStage1_discrete_tcnn1/temporal_conv/weights
TrainStage1_discrete_tcnn1/temporal_conv/biases
TrainStage1_discrete_tcnn1/softmax_linear_car_discrete/weights
TrainStage1_discrete_tcnn1/softmax_linear_car_discrete/biases
----------------------------------------
 Gradient Clipping On
Traceback (most recent call last):
  File "train.py", line 583, in <module>
    tf.app.run()
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 580, in main
    train()
  File "train.py", line 399, in train
    apply_gradient_op = opt.apply_gradients(grads, global_step=global_step)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/momentum.py", line 66, in _create_slots
    self._zeros_slot(v, "momentum", self._name)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.py", line 766, in _zeros_slot
    named_slots[_var_key(var)] = slot_creator.create_zeros_slot(var, op_name)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 174, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 146, in create_slot_with_initializer
    dtype)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/slot_creator.py", line 66, in _create_slot_var
    validate_shape=validate_shape)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1065, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 962, in get_variable
    use_resource=use_resource, custom_getter=custom_getter)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 367, in get_variable
    validate_shape=validate_shape, use_resource=use_resource)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 352, in _true_getter
    use_resource=use_resource)
  File "/home/zrachlin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 682, in _get_single_variable
    "VarScope?" % name)
ValueError: Variable conv1/weights/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by gy20073** [comment]
Can you try with tensor flow 0.11? Our code is not compatible with the latest version, at least for the LSTM part.
